Corrections in Terraform manifests
yandex-cloud-examples/yc-data-proc-to-data-proc pull request #5
Opened 2024-12-10 09:42 UTC by mikhaildoc-documentat

2024-12-28 05:28 UTC, Odyvia42 requested changes

2024-12-28 05:28 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
>      protocol       = "ANY"
Не могу комментить в нужной строке, поэтому здесь.
В строке [125](https://github.com/yandex-cloud-examples/yc-data-proc-to-data-proc/blob/76174bab497645f38482d15abc4a4463ec00fdcb/dataproc-to-dataproc.tf#L125) давай изменим название ресурса, в котором назначается роль `storage.admin`, с `s3-editor` на `s3-admin`. 
Соответственно, заменить надо будет и во всех референсах на этот ресурс.

2024-12-28 05:28 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
> +    yandex_resourcemanager_folder_iam_binding.s3-editor
```suggestion
    yandex_resourcemanager_folder_iam_binding.s3-admin
```

2024-12-28 05:28 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
> +    yandex_resourcemanager_folder_iam_binding.s3-editor
```suggestion
    yandex_resourcemanager_folder_iam_binding.s3-admin
```

2024-12-28 05:28 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Здесь было правильно. Давай вернём как было.

2024-12-28 05:28 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Здесь было правильно. Давай вернём как было.

2024-12-28 05:28 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
Давай пропишем в обоих кластерах зависимости от ресурсов с ролями `dataproc.agent`  и `dataproc.provisioner`, как в других манифестах.

2025-01-09 10:16 UTC, mikhaildoc-documentat commented on dataproc-to-dataproc.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так, как я исправил. См. пример в https://developer.hashicorp.com/terraform/language/functions/file

2025-01-09 10:16 UTC, mikhaildoc-documentat commented on dataproc-to-dataproc.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так, как я исправил. См. пример в https://developer.hashicorp.com/terraform/language/functions/file

2025-01-09 10:17 UTC, mikhaildoc-documentat commented on dataproc-to-dataproc.tf
Они там есть, см. строчки 172 и 220

2025-01-10 04:17 UTC, Odyvia42 commented on dataproc-to-dataproc.tf
Да, точно, просмотрел. Тогда вопрос снимается.

2025-01-10 05:23 UTC, Odyvia42 approved these changes

2025-01-10 13:59 UTC, lanieuszko approved these changes

2025-01-10 13:59 UTC, merged